### ISSUE TITLE
Related Project

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/automation#1]
Taken from https://github.com/nodejs/TSC/issues/392#issue-267389876

* [The Github bot](https://github.com/nodejs/github-bot)
* [node-review](https://github.com/evanlucas/node-review) (See [discussion](https://github.com/nodejs/admin/issues/23) on moving them into the foundation)
* [branch-diff](https://github.com/rvagg/branch-diff) and [changelog-maker](https://github.com/rvagg/changelog-maker) (See [discussion](https://github.com/nodejs/admin/issues/16) on moving them into the foundation)
* [core-validate-commit](https://github.com/evanlucas/core-validate-commit) if @evanlucas agrees to move it into the foundation
* [node-core-utils](https://github.com/joyeecheung/node-core-utils) (still in rapid development, can be transferred when it's ready)
* [lts](https://github.com/continuationlabs/lts)
* IRC/gitter/slack Slurp ([current](https://github.com/piscisaureus/slurp))

**Comment by joyeecheung** [comment]
Also I am working on https://github.com/joyeecheung/node-core-utils, it can be transferred when it's ready (right now changes too fast and too much force-pushing lol)

**Comment by MylesBorins** [comment]
@joyeecheung please feel free to add to the original post

(same to anyone else reading this)

**Comment by refack** [comment]
I've thrown the name `GYP` around... It's not an obvious fit, but this SIG is the closest home currently available.

**Comment by refack** [comment]
P.S. Using the [project boards](https://github.com/nodejs/automation/projects) (in addition to labels) seems like a good fit.

**Comment by maclover7** [comment]
To at least start off, would it make sense to structure nodejs/automation as a [Lerna](https://github.com/lerna/lerna) repo, and import `branch-diff`, `changelog-maker`, and `core-validate-commit` that way? So that way at least all of the modules are in one place, and then we can try and refactor/go from there.

**Comment by joyeecheung** [comment]
@maclover7 Hmmm..what do we gain by moving their source code into one repository tho? If we want to distribute them together we can just make a package that set up multiple `bin` entries..

**Comment by gibfahn** [comment]
I guess the downside to that is that we'd lose commit history for the existing repos too.

**Comment by joyeecheung** [comment]
> I've thrown the name GYP around... It's not an obvious fit, but this SIG is the closest home currently available.

@refack Hmm..do we still plan to use GYP, like, forever..? I guess at some point we might have to switch to GN? If so I guess it makes more sense to focus on the transition (although that sounds more like core stuff or build stuff)

**Comment by maclover7** [comment]
>Hmmm..what do we gain by moving their source code into one repository tho?

@joyeecheung My thought was that it's easier to keep all of the tools automation might be maintaining in a single place. Also, if some tools might be combined/sharing logic, it would be easier to keep everything together (PRs could affect multiple tools, easier to review via one repo).

> I guess the downside to that is that we'd lose commit history for the existing repos too.

@gibfahn I have to refresh my git-fu, but I think we can do a "subtree merge" to keep all of the existing history

**Comment by refack** [comment]
> @refack Hmm..do we still plan to use GYP, like, forever..? I guess at some point we might have to switch to GN? If so I guess it makes more sense to focus on the transition (although that sounds more like core stuff or build stuff)

Just for context (still not sure if this is the proper home)
1) `GYP` IMHO is a great tool. BTW even outside of the node ecosystem it's more popular than `gn`
2) We should start maintaining it properly, i.e. new platform & bug fixes
3) The "optimal" transition IMHO is to [`gyp.js`](https://github.com/indutny/gyp.js), not `gn` (V8 building issue has a [resolution plan](https://docs.google.com/document/d/1gvHuesiuvLzD6X6ONddxXRxhODlOJlxgfoTNZTlKLGA/edit#heading=h.13l47ngephw))
4) That's because of the substantial ecosystem investment in addon build scaffolding via `node-gyp`
5) P.S. `node-gyp`

**Comment by refack** [comment]
> I guess the downside to that is that we'd lose commit history for the existing repos too.

There's a way to graft git trees together, so we'll only lose the GitHub meta history. I'm also not crazy about adding 7-10 repos.
Ref: [Monorepos in the wild](https://medium.com/@maoberlehner/monorepos-in-the-wild-33c6eb246cb9) etc.

**Comment by joyeecheung** [comment]
> Just for context (still not sure if this is the proper home) ...

@refack Thanks for the context (and I think this is probably not something that should be handed over to the automation team :S...this is related to how the core is built & how addons are built so deserves its own taskforce)

**Comment by refack** [comment]
Another tool https://github.com/nodejs/nodejs-latest-linker - ATM it does not create a link for latest nightly nor latest v8-canary.
Refs: https://github.com/nodejs/build/issues/908

**Comment by Tiriel** [comment]
Just to keep moving, where do we get from here?

I do like the idea of a monorepo, but how do we really implement it and transfer repos from various places to here?

**Comment by joyeecheung** [comment]
@maclover7 mentioned Lerna (https://github.com/nodejs/automation/issues/1#issuecomment-338982704), I think this looks like a good tool to get things started?

**Comment by Tiriel** [comment]
LGTM!

**Comment by maclover7** [comment]
👍 whenever nodejs/TSC/issues/406 is approved, I'll start moving stuff in :)

**Comment by refack** [comment]
> 👍 whenever nodejs/TSC#406 is approved, I'll start moving stuff in :)

I have a snippet that does git tree grafting.

**Comment by Tiriel** [comment]
Just wanted to say: I am deeply excited to be part of all of this.
More than I care to admit in fact.

This is just awesome!

**Comment by Tiriel** [comment]
Can't edit issues on this repo (yet?) but the link for node-core-utils should be updated in the issue, still points toward the old repo.

**Comment by rvagg** [comment]
FYI my node tools have grown out of this repo https://github.com/rvagg/iojs-tools, there's still a few in there you can have if anyone cares. *pr-metadata* is something I've still found helpful but the lack of a GitHub API for the review feature has made it less useful (maybe there's an API or we'll get one soon). Evan's Chrome extension seems to do a more complete job for now.

**Comment by joyeecheung** [comment]
@rvagg By "GitHub API for the review feature" do you mean "GitHub API for getting reviewers and their review status"? If so that's available now and is being used by [get-metadata](https://github.com/nodejs/node-core-utils#get-metadata), which is a CLI alternative to node-review. The GraphQL query we use to get the reviews is [here](https://github.com/nodejs/node-core-utils/blob/master/queries/Reviews.gql).

**Comment by rvagg** [comment]
Cool, wasn't even available on GraphQL last time I looked. If you have a new utility that does this work then that's great and you don't need mine!
