### ISSUE TITLE
Can we automate appending changelogs to a release

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/automation#14]
https://github.com/nodejs/node/releases

There is an api for editing a release... so this seems pretty reasonable
https://developer.github.com/v3/repos/releases/#edit-a-release

**Comment by Tiriel** [comment]
That do seem to be a good idea. And most of the required tools are already here I'd say.

This brings me a question.

If I'm not mistaken, GitHub v4 API does not currently support mutating repos and most of their attributes. So, for features like this one, do we mix API versions we call? Do we try to keep some measure of consistency?

**Comment by joyeecheung** [comment]
@Tiriel I'd say when we are not in a monorepo, the best thing to do is go with the API that can meet most of your needs (or the primary one), and add another if the features are lacking. The GraphQL API does [support mutations](https://developer.github.com/v4/guides/forming-calls/#example-mutation), but from a quick search in the explorer I don't think release mutations are supported. In this case the v3 API seems to be the one to go with.

**Comment by Tiriel** [comment]
@joyeecheung Yup, that was my point. I searched through the v4 API reference and didn't see release mutations.

Anyway, I'm ok with this rule. Consistency in monorepo, and what we need elsewhere!
I guess then this could be implemented!
