### ISSUE TITLE
CitGM testing Node-Core-Utils?

### ISSUE THREAD

**Issue by Tiriel** [nodejs/automation#16]
Small suggestion:

The npm install issue we had earlier today had me thinking:
Shouldn't we test our releases in some way with earlier Node releases?

I mean, I understand there's a great tool for that in the project, so maybe we could take advantage?
Not necessarily for really old versions, but at least current lts + latest version?

Maybe dumb idea, but at least we can talk about it ^^

**Comment by joyeecheung** [comment]
I'd say let's just skip LTS and go with current, considering most of its users should have master build on their machines already.

**Comment by joyeecheung** [comment]
Also I am a bit confused, does the OP mean we add node-core-utils to citgm's lookup.json?

**Comment by Tiriel** [comment]
That's a fair point. As I don't know if there are many backporting PRs, testing against previous versions may not be relevant. 

For the record, adding Node-core-utils to the lookup.json wasn't my intention at first. More like using citgm on our side in our test suite if it was possible. 
Dumb idea, sorry!

**Comment by joyeecheung** [comment]
@Tiriel Do you mean we should test node-core-utils against different releases? I think we can just add new entries to travis or appveryor configs for that?

**Comment by Tiriel** [comment]
Indeed we can, that was more to enable testing before pushing. But it's indeed not relevant in fact.

**Comment by Tiriel** [comment]
Closing as it's irrelevant :)

**Comment by refack** [comment]
The point of CitGM is to test that new changes in node-core do not break userland packages. I'm not sure if ATM this tool does anything fragile, but even if it's still straight forward the cost of adding ti to CitGM is low. Just read https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md#submitting-a-module-to-citgm and open a PR similar to https://github.com/nodejs/citgm/pull/475

**Comment by Tiriel** [comment]
@joyeecheung I'll leave it to you to decide if we should reopen the issue or not, or make a PR to citgm or not.

In any case, I'm willing to do it, if everyone thinks it's a good idea

**Comment by joyeecheung** [comment]
@Tiriel If the CIGTM team thinks it's a good idea then I am all for it (which reminds me we need to put an "engines" field in our package.json and skip lower versions of Node). Do you want to [open a PR in the citgm repo](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md#submitting-a-module-to-citgm)?

**Comment by Tiriel** [comment]
@joyeecheung No problem! Thanks!
