### ISSUE TITLE
Include collaborators/team members in the README?

### ISSUE THREAD

**Issue by alopezsanchez** [nodejs/automation#17]
Like [nodejs/node README](https://github.com/nodejs/node#current-project-team-members) does.

**Comment by joyeecheung** [comment]
So..one thing to consider. Listing people in the README makes it less quite for inactive people to leave later, as is the case with Node core. It puts extra expectations/responsibilities  on the collaborators, even for the people in the collaborator team who are already TSC members. An informal team makes things simpler.

That said, I don't mind listing people in the README if everyone listed approve the PR.

**Comment by Tiriel** [comment]
Maybe then could we just list the Collaborators, and not the team members? I get your point @joyeecheung but I feel it would still help identify who to ping on specific questions, but maybe I'm wrong.

**Comment by MM422** [comment]
I agree with @Tiriel , I think the list will become hard to maintain if you list all members on our team.

**Comment by joyeecheung** [comment]
@Tiriel well if it's just for the ping, you can ping the whole team with `@nodejs/automation` and `@nodejs/automation-collaborators` and `@nodejs/automation-admins`(I've put the text in backticks because I am not actually pinging everyone in this thread, but you know.)

(Or maybe I should ping everyone in this thread?)

**Comment by refack** [comment]
I'm +1 on listing, as all other WGs do, but I don't feel strongly.

**Comment by vicky002** [comment]
I don't think it's needed.  If will be an extra pain to keep updating it with the time, adding removing etc. Also, [NodeJS/node](https://github.com/nodejs/node#current-project-team-members), all the email addresses are public, it sometimes leads to spam, as per my experience. 

I agree with @joyeecheung, one can ping the whole team, whenever it's needed.

**Comment by Tiriel** [comment]
> well if it's just for the ping, you can ping the whole team with `@nodejs/automation` and `@nodejs/automation-collaborators` and `@nodejs/automation-admins` (I've put the text in backticks because I am not actually pinging everyone in this thread, but you know.)

True, but as said, it also seems to be some sort of "standard" amongst aother teams/WG. I do think it helps putting "faces" on a project. But indeed, listing everyone and keeping the list up to date would be a pain in the arse, so collaborators only seems a good compromise to me.

And just in case, we can make this list on a "voluntary listing oneself" basis. Each person can opt-out of the listing if they want (without actually opting-out of the team/collaborators).

Would that satisfy everyone?

**Comment by joyeecheung** [comment]
As mentioned in https://github.com/nodejs/diagnostics/issues/127#issuecomment-349404400 we could actually let the bot sync the team membership and the README.
