### ISSUE TITLE
Idea: A twitter bot to thank new contributors

### ISSUE THREAD

**Issue by jasnell** [nodejs/automation#21]
One small automation idea: when a PR lands from a brand new contributor, it would be cool to have a Twitter bot that automatically posts a thank you tweet with a link to the PR. Might be a cool way to give some recognition.

**Comment by maclover7** [comment]
Interesting idea! The 24 Pull Requests project has a [Twitter bot](https://twitter.com/24prbot) that tweets whenever a PR is opened, and that code is [OSS](https://github.com/24pullrequests/tweets), maybe could be adapted to Node's requirements? cc @andrew

**Comment by Tiriel** [comment]
That is actually a super cool idea!

I'd like to work on such a bot, if everyone's cool with this

**Comment by fhinkel** [comment]
Ideally, we should check with the contributors though if they want to be mentioned on Twitter.

**Comment by Trott** [comment]
Unarchived this repo so I could close all the PRs and issues. Will re-archive when I'm done.
