### ISSUE TITLE
greenkeeper-like feature for ncu-team

### ISSUE THREAD

**Issue by targos** [nodejs/automation#24]
We could use the github bot to listen to the org's `membership` event and automatically open a PR to update the member list in readmes.

Just an idea, implementation still should thought of (how would the bot know which teams are relevant and which readmes need update)

**Comment by joyeecheung** [comment]
I think we would still need to lift the restriction of org-wise hooks for that first? See https://github.com/nodejs/github-bot#nodejs-github-bot

cc @nodejs/tsc

**Comment by mcollina** [comment]
I think the reason for the restriction is no more. I do not know if the restriction has been actually lifted.
However, 👍  in doing.

**Comment by ChALkeR** [comment]
@joyeecheung Which permission scopes would be required for that?
I suppose that the bot could be just a regular member of the org to be able to do that, without any elevated permissions. I did not look close enough, though.

Not sure about the hooks, but checking the list each hour should be doable without those.

**Comment by joyeecheung** [comment]
@ChALkeR Yes, polling should work as well

**Comment by Trott** [comment]
Unarchived this repo so I could close all the PRs and issues. Will re-archive when I'm done.
