### ISSUE TITLE
Use ncu-team in create-node-meeting-artifacts

### ISSUE THREAD

**Issue by gibfahn** [nodejs/automation#25]
See https://github.com/nodejs/TSC/issues/491#issuecomment-364935114, it would be great if [mhdawson/create-node-meeting-artifacts](https://github.com/mhdawson/create-node-meeting-artifacts) could pull the team lists from GitHub, probably by using [`ncu-team`](https://github.com/nodejs/node-core-utils/blob/master/docs/ncu-team.md).? The current lists is [here](https://github.com/mhdawson/create-node-meeting-artifacts/blob/master/templates/invited_tsc). 

cc/ @mhdawson @richardlau

**Comment by Trott** [comment]
Unarchived this repo so I could close all the PRs and issues. Will re-archive when I'm done.
