### ISSUE TITLE
doc REPLACEME linter/fixer

### ISSUE THREAD

**Issue by refack** [nodejs/automation#29]
```
  - version: REPLACEME
    pr-url: REPLACEME
```

When originally authoring a PR that has API doc changes, you can't know the pr-url apriori. So this issue can't be trivially linted.
We should either:
1. Lint only via `ncu` before landing
2. Get Jenkins to suggest change (if PR ID is available)
3. Fail lint so PRs don't get green CI until this is fixed
4. Create a `REPLACEME` replace tool for releasers, that deduces the pr-url

**Comment by addaleax** [comment]
I think anything except maybe 4. would be okay, and these suggestions don’t necessarily conflict with each other. 1. would be very good to have, in any case.

**Comment by BridgeAR** [comment]
Hm, thinking about it: 4 would be the "easiest" one for authors. We have the information in the individual commit, it would just not be completely trivial to find the correct entry.

So to me all options sound good.

**Comment by Trott** [comment]
Unarchived this repo so I could close all the PRs and issues. Will re-archive when I'm done.
