### ISSUE TITLE
Commit Queue

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/automation#3]
The earliest I remember this being brought up was by @refack 

A commit queue is a process for automating the landing of commits and managing of multiple branches.

This is a potential way to fix #2 

For inspiration here is the design doc for the [Chromium Commit Queue](https://dev.chromium.org/developers/testing/commit-queue/design)

> The CQ polls rietveld for CLs that are ready to be committed. The Chromium's fork of Rietveld has a 'Commit' checkbox. When the author or the reviewer checks it, it will be included in the next poll. Once the CQ learns about the CL, it verifies the author or one of the reviewers approving this CL is a full committer, then runs the presubmit checks, then runs try jobs and then commit the patch on the behalf of the author, faking its credential. The whole project is written in python.

**Comment by joyeecheung** [comment]
The Rust project has a https://github.com/bors IIUC it pretty much does the same kind of stuff, but on Github. Pick [a merged PR](https://github.com/rust-lang/rust/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%20) to see what it does.

**Comment by jasnell** [comment]
Until we have a consistently green and consistently *functioning* CI, this is going to be dang near impossible to do. There is too much in the landing process that requires manual intervention, not the least of which is interpreting CI results.

**Comment by MylesBorins** [comment]
@jasnell it could be kicked off only at the point you would manually do it yourself. That would remove the potential for error when landing the commit

**Comment by refack** [comment]
Refs: https://github.com/nodejs/build/issues/705
There's seems to be prior art, I'll try to find references.

**Comment by bnoordhuis** [comment]
> Until we have a consistently green and consistently functioning CI, this is going to be dang near impossible to do.

It's not a big deal in practice.  Rust doesn't have that either, getting something landed sometimes takes a few retries, but it's okay because it's automated.

I for one would be very pleased if this went through.

**Comment by jasnell** [comment]
![hn4cl2lfiu4xm](https://user-images.githubusercontent.com/439929/31944217-2d3042a2-b880-11e7-8e08-2d539b8266d6.gif)

;) Ok... So long as it is focused on the after CI bits, I'm +1. Eventually we need to take a serious look at CI tho

**Comment by ofrobots** [comment]
If anything the commit queue increases the incentive to fix flakiness.

**Comment by joyeecheung** [comment]
Some thoughts on the next step of `node-core-utils`: https://github.com/joyeecheung/node-core-utils/issues/10 , could potentially be used by the bot, right now the goal is "good enough for human to use".
