### ISSUE TITLE
Github team management (reply here if you want to join)

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/automation#4]
1. Anyone interested in joining but does not have the team admin access, please indicate your interest in this thread. (BTW Node.js organization owners should have the access)
2. I did not make this team a child team of build because that would grant access to repos that contain secrets and stuff. I am not that well-versed with Github teams so let me know if there is a better way to organize things better

IMPORTANT: if you are not already a member of the Node.js organization, please read https://github.com/nodejs/automation/issues/4#issuecomment-340736319 about the purpose of this team, make sure to read our [Code of Conduct](https://github.com/nodejs/TSC/blob/master/CODE_OF_CONDUCT.md) and agree on it before you reply.

**Comment by tniessen** [comment]
I requested to join.

**Comment by Tiriel** [comment]
GitHub-noob question: How do we check we have the "team admin access"?
I currently see myself as team member on the org page, but I don't seem to have any particular access or right.

> I did not make this team a child team of build because that would grant access to repos that contain secrets and stuff. I am not that well-versed with Github teams so let me know if there is a better way to organize things better

Seems clearer to me that way!

**Comment by gibfahn** [comment]
You can see if you're a member by looking at the team list: https://github.com/orgs/nodejs/teams/automation/members (@tiriel you are a member).

@joyeecheung did you mean to give the automation team access to the automation repo? If so I think it's done through here: https://github.com/orgs/nodejs/teams/automation/repositories

**Comment by Tiriel** [comment]
@gibfahn Yup, I saw that I'm (which is totally awesome for me!), my question was precisely about the "admin access" @joyeecheung was talking about.
But you explain it better :smile: 
Thanks!

**Comment by gibfahn** [comment]
For anyone coming across this thread and not knowing what exactly the team is forj, this issue has the background: https://github.com/nodejs/TSC/issues/392

**Comment by al-k21** [comment]
I would like to help automate Node.js project.

**Comment by joyeecheung** [comment]
From now on I will add a ❤️ when an invitation is sent out for the request :D...

**Comment by BethGriggs** [comment]
I'd like to help out here :)

**Comment by refack** [comment]
Happy to help.

**Comment by evenstensberg** [comment]
@joyeecheung Do we have a slack or IRC for the automation team?

**Comment by joyeecheung** [comment]
@ev1stensberg Not yet..how about gitter? (proposing that because it's just easy to set up..)

**Comment by joyeecheung** [comment]
I think we can start listing team members in README after a week. Right now the number is still growing..

**Comment by aashil** [comment]
I would like to help.

**Comment by MM422** [comment]
@joyeecheung Hi! I would be really happy to join this team. Please let me help with this project. :smiley:

**Comment by vicky002** [comment]
@joyeecheung  I have good experience in automation and testing. Would love to work on this, always prefer open source projects over private paid projects. 🙂

**Comment by priyank-p** [comment]
@joyeecheung, I would like to be in too! Please let me in. 😃

**Comment by bnb** [comment]
I would love to join, and contribute when I have cycles! ❤️

**Comment by kinsomicrote** [comment]
Any requirements for those who want to be part?

**Comment by alopezsanchez** [comment]
@joyeecheung Hello! My name is Alex.
I work with Node.js everyday and I would like to join the team and collaborate with all of you! 😃

**Comment by JasonEtco** [comment]
Hiya! I'd like to join (especially to help out with the GitHub side of automation). Don't have a ton of time, but I'll do what I can 💪

**Comment by matchai** [comment]
Howdy! 🤠
I'd love to help out in any way I can.

**Comment by riyadhalnur** [comment]
I'm interested 😃

**Comment by nickooms** [comment]
I love Node.js and JavaScript and have been using it on a daily basis for a very long time.
Improving code coverage sounds like a great plan, but a changing API wil probably make it a lot harder.
And then I realise I have no clue whatsoever if standards for describing API changes even exist... 😃
Improving tooling, I wanna help out in any way I can!

**Comment by joyeecheung** [comment]
Hi all, just want to make sure we are on the same page...this team is about:

> ... building tools, bots and scripts that help Node.js collaborators maintain the Node.js project.

for example, we are building [node-core-utils](https://github.com/joyeecheung/node-core-utils/) because to land a PR in Node.js, one would do a lot of checks, grab some metadata out of the thread, amend those in the commit message before pushing it to remote. It would make our lives easier if this can be done automatically.

So basically this team is here mostly to serve the Node.js collaborators (i.e. people who have commit access in [nodejs/node](https://github.com/nodejs/node)) and members of other Node.js working group. I noticed a lot of you have not participated in the Node.js core or other Node.js working groups before, so you might get confused when people ping @nodejs/automation for something they want, if you do not know about the existing processes and conventions that those needs are base on.

That said, being in this team does not require you to be a collaborator or a working group member, just want to make sure everybody knows what they are getting themselves into.

Also there is another thing that I have not mentioned before, is that we expect people in the Node.js organization to follow our [Code of Conduct](https://github.com/nodejs/TSC/blob/master/CODE_OF_CONDUCT.md).

<b>For now I will temporarily remove people who have not opened any PR within the Node.js organization from the automation team. </b> If you are removed, or if you have replied in this thread before but have not accept a membership invitation, please chat with me privately on [gitter](https://gitter.im/nodejs/automation)(click on my icon on the right) or send me a email (`joyeec9h3[at]gmail.com`) to confirm that you still want to join and are willing to follow our code of conduct.  This does not mean that we don't want you to be part of us, just to make sure people sign up on the CoC before they join.

Sorry for the misunderstanding.

BTW this is the query that I use to search activities within the organization:

```GraphQL
query SearchActivityByUser($queryString: String!) {
  search(query: $queryString, type: ISSUE, first: 100) {
    nodes {
      ... on PullRequest {
        url
        publishedAt
        title
        bodyText
      }
    }
  }
}
```

Where queryString is `author:${github_username_here} org:nodejs type:pr`

**Comment by joshholl** [comment]
I would like to be involved as well

**Comment by richardlau** [comment]
I would also like to help.

**Comment by joyeecheung** [comment]
@kinsomicrote 

> Any requirements for those who want to be part?

Not really, as long as you've read the [Code of Conduct](https://github.com/nodejs/TSC/blob/master/CODE_OF_CONDUCT.md) and agree on it.

**Comment by kinsomicrote** [comment]
I am interested.

**Comment by NullDev** [comment]
Is this still open? I'd be interested!

**Comment by bnb** [comment]
Definitely a need still, though I'm not sure if there's been any recent developments from the Automation team!

**Comment by joyeecheung** [comment]
@NLDev Not really, I think I am going to close this for now, sorry.

@bnb Yes, there are not much developments from the automation team for now. There are a lot of issues open for grabs but there are not many PRs submitted to fix them. I opened this issue to recruit people interested in helping out, especially those who are not members in the organization, but there are only a few people who has been helping out with the automation projects and most of them are already members (though I am happy to see there are a few contributors who are not previously involved with the Node.js organization). I am sorry but it seems opening an issue like this is not enough to get more helping hands, so I am going to close this and think about a better way to do that.

I think the biggest problem with this approach is that we don't have enough contributing guides for existing projects, so people who have not been involved would have trouble finding where to start - this could probably be alleviated once we get the monorepo idea up and running but I don't think it's going to happen soon since most people interested are busy working on other stuff in the organization.

**Comment by joyeecheung** [comment]
FYI: if you are still interested in helping, there are a few issues open in https://github.com/nodejs/node-core-utils/issues that could use some help, and I am still actively maintaining it. Other projects listed in this project's README could also use some help but they are less active at the moment.

**Comment by kaue** [comment]
@joyeecheung looks like i lost my badge, I had some contributions to the website in the past, i wounder whats required now days to get involved into the team again :)
