### ISSUE TITLE
Node.js clone repo for testing

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/automation#5]
I've searched the organization for "testing" repos and have not found one. We should have a repo forking from the `nodejs/node` repo for testing bots/scripts. Any other ideas on how this should be managed?

**Comment by joyeecheung** [comment]
Similar to what https://github.com/nodejs/node-v8 is (not sure if we need a CI to update it).

**Comment by joyeecheung** [comment]
I have created [node-auto-test](https://github.com/nodejs/node-auto-test)

**Comment by refack** [comment]
Just FYI: there are at least two forks that were created as discussion hubs [worker](https://github.com/nodejs/worker) &  [ffi](https://github.com/nodejs/ffi) and code work hasn't started on them.

**Comment by joyeecheung** [comment]
I am going to close this because I think we can give node-auto-test a try first. Also I have made it a repo that our team controls now.

**Comment by joyeecheung** [comment]
Oh wait, I knew I was forgetting something...there is https://github.com/TestOrgPleaseIgnore !

**Comment by phillipj** [comment]
The TestOrgPleaseIgnore org has been really valuable when playing around with the github bot. Although writing different types of tests can get us far, there's really nothing like testing against the real deal (read github.com).

Only having the [node](https://github.com/nodejs/node) core repo isn't enough for the things we've been testing either.

Although we haven't done so in the github bot yet, an organization like that could even be used for integration tests I imagine.
