### ISSUE TITLE
Brigade

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/automation#7]
https://github.com/Azure/brigade

This is really interesting tool for writing CI / CD pipelines using k8s with JavaScript (node...ish).

I wonder if it could be a cool way to build some tools. I can likely stand up a test cluster for us to experiment with

**Comment by Tiriel** [comment]
My skills may not be strong enough yet, but although this does indeed seem **very** cool, I'm wondering if it is really needed for our use?

(This is a true question, is consider myself a noob and I'm eager to learn, not harm intended)

**Comment by joyeecheung** [comment]
This looks interesting, I have thought about other serverless solutions for implementing bots but not really sure which one to go to. Wasn't aware of this, looks like a good candidate, although that requires a kubernetes cluster so it might complicate matters, but doesn't hurt to give it a try.

**Comment by phillipj** [comment]
+1 for trying something different than the traditional virtual machine with running node processes style of running things.

As long as we could get a hold of a managed kubernetes cluster, meaning something we wouldn't have to maintain & take care of 24/7, I'd absolutely be willing to give this a shot. Either for new stuff or extract a piece of the github bot, like PR labelling?
